export const headerData = [
  {
    id: 1,
    title: "Anasayfa",
    link: "/",
    catChild: 0,
  },
  {
    id: 2,
    title: "Kurumsal",
    link: "/kurumsal",
    catChild: 0,
  },
  {
    id: 3,
    title: "Ürünler",
    link: "",
    catChild: 3,
  },
  {
    id: 4,
    title: "ENDÜSTRİ",
    link: "",
    catChild: 4,
  },
  {
    id: 5,
    title: "Çözümler",
    link: "",
    catChild: 4,
  },
  {
    id: 6,
    title: "Haberler",
    link: "",
    catChild: 2,
  },
  {
    id: 7,
    title: "Download",
    link: "",
    catChild: 2,
  },
  {
    id: 8,
    title: "İLETİŞİM",
    link: "/contact",
    catChild: 0,
  },
];

export const childMenu = [
  {
    id: 1,
    title: "Hakkımızda",
    url: "/",
    catName: "ŞİRKET",
    catChild: 0,
  },
  {
    id: 2,
    title: "Vizyonumuz",
    url: "/",
    catName: "ŞİRKET",
    catChild: 0,
  },
  {
    id: 3,
    title: "Misyonumuz",
    url: "/",
    catName: "ŞİRKET",
    catChild: 0,
  },

  {
    id: 11,
    title: "Masaüstü Uygulama",
    url: "",
    catName: "Ürünler",
    catChild: 3,
  },
  {
    id: 12,
    title: "Mobil Uygulama",
    url: "/",
    catName: "Ürünler",
    catChild: 2,
  },
  {
    id: 13,
    title: "Web Uygulama",
    url: "/web-uygulama",
    catName: "Ürünler",
    catChild: 0,
  },
  {
    id: 21,
    title: "İnşaat Mühendisliği",
    url: "/insaat-muhendisligi",
    catName: "ENDÜSTRİ",
    catChild: 0,
  },
  {
    id: 22,
    title: "Medical",
    url: "/medical",
    catName: "ENDÜSTRİ",
    catChild: 0,
  },
  {
    id: 23,
    title: "Enerji",
    url: "/enerji",
    catName: "ENDÜSTRİ",
    catChild: 0,
  },
  {
    id: 24,
    title: "E-ticaret",
    url: "/e-ticaret",
    catName: "ENDÜSTRİ",
    catChild: 0,
  },
  {
    id: 31,
    title: "Görüntü İşleme",
    url: "/goruntu-isleme",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 32,
    title: "3D CAD Programlama",
    url: "/3d-cad-programlama",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 33,
    title: "ERP(PC, mobil, web)",
    url: "/erp",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 34,
    title: "E-ticaret",
    url: "/e-ticaret",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 34,
    title: "Web Programlama",
    url: "/web-uygulama",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 35,
    title: "Mobil Programlama",
    url: "/",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 36,
    title: "Masaüstü Programlama",
    url: "/",
    catName: "Çözümler",
    catChild: 0,
  },
  {
    id: 41,
    title: "Basında",
    url: "/basinda",
    catName: "Haberler",
    catChild: 0,
  },
  {
    id: 42,
    title: "Sosyal Medya",
    url: "/sosyal-medya",
    catName: "Haberler",
    catChild: 0,
  },
  {
    id: 51,
    title: "İskele",
    url: "/iskele",
    catName: "Download",
    catChild: 0,
  },
  {
    id: 52,
    title: "Yığma",
    url: "/yigma",
    catName: "Download",
    catChild: 0,
  },
];

export const subChildMenu = [
  {
    id: 11,
    title: "İskele",
    url: "/iskele",
    catName: "Masaüstü Uygulama",
  },
  {
    id: 12,
    title: "Yığma",
    url: "/yigma",
    catName: "Masaüstü Uygulama",
  },
  {
    id: 13,
    title: "Ayak Analiz",
    url: "/ayak-analiz",
    catName: "Masaüstü Uygulama",
  },
  {
    id: 21,
    title: "Doğalgaz Sayacı Okuma",
    url: "/dogalgaz-sayac",
    catName: "Mobil Uygulama",
  },
  {
    id: 22,
    title: "Elektrik Sayacı Okuma",
    url: "/elektrik-sayac",
    catName: "Mobil Uygulama",
  },
  {
    id: 23,
    title: "Statik Proje Bedeli Hesaplama",
    url: "/proje-bedel",
    catName: "Mobil Uygulama",
  },
  {
    id: 31,
    title: "Yığma",
    url: "/yigma",
    catName: "İnşaat Mühendisliği",
  },
  {
    id: 32,
    title: "Kentsel Dönüşüm Bilgi Sistemi",
    url: "/kentsel-donusum",
    catName: "İnşaat Mühendisliği",
  },
  {
    id: 33,
    title: "İskele",
    url: "/iskele",
    catName: "İnşaat Mühendisliği",
  },
  {
    id: 34,
    title: "Statik Proje Bedeli Hesaplama",
    url: "/proje-bedel",
    catName: "İnşaat Mühendisliği",
  },
  // {
  //   id: 41,
  //   title: "ERP Yazılım ve Danışmanlık",
  //   url: "/erp",
  //   catName: "Web Programlama",
  // },
  // {
  //   id: 42,
  //   title: "MLM Özellikli E-ticaret Portalı",
  //   url: "/e-ticaret",
  //   catName: "Web Programlama",
  // },
  // {
  //   id: 43,
  //   title: "Kentsel Dönüşüm Bilgi Sistemi",
  //   url: "/kentsel-donusum",
  //   catName: "Web Programlama",
  // },
  {
    id: 51,
    title: "ERP Yazılım ve Danışmanlık",
    url: "/erp",
    catName: "Web Uygulama",
  },
  {
    id: 52,
    title: "MLM Özellikli E-ticaret Portalı",
    url: "/e-ticaret",
    catName: "Web Uygulama",
  },
  {
    id: 53,
    title: "Kentsel Dönüşüm Bilgi Sistemi",
    url: "/kentsel-donusum",
    catName: "Web Uygulama",
  },
  {
    id: 61,
    title: "Ayak Analiz",
    url: "/ayak-analiz",
    catName: "Medical",
  },
];
