export const workData = [
  {
    id: 1,
    url: "/assets/Images/medikal.png",
    alt: "Magenta Ayak Analizi",
    title1: "MAGENTA",
    title2: "AYAK ANALİZİ",
    link: "/ayak-analiz",
  },
  {
    id: 2,
    url: "/assets/Images/mobil-programlama.png",
    alt: "Doğalgaz Sayacı Okuma",
    title1: "DOĞALGAZ",
    title2: "SAYAÇ OKUMA",
    link: "/dogalgaz-sayac",
  },
  {
    id: 3,
    url: "/assets/Images/civil.png",
    alt: "Elektrik Sayacı Okuma",
    title1: "ELEKTRİK",
    title2: "SAYAÇ OKUMA",
    link: "/elektrik-sayac",
  },
  {
    id: 4,
    url: "/assets/Images/ERP-rapor.png",
    alt: "Statik Proje Bedeli Hesaplama",
    title1: "STATİK PROJE BEDELİ",
    title2: "HESAPLAMA",
    link: "/proje-bedel",
  },
  {
    id: 5,
    url: "/assets/Images/ERP-rapor.png",
    alt: "ERP Yazılım ve Danışmanlık",
    title1: "ERP YAZILIM VE",
    title2: "DANIŞMANLIK",
    link: "/erp",
  },
  {
    id: 6,
    url: "/assets/Images/ERP-rapor.png",
    alt: "MLM Özellikli E-ticaret Portalı",
    title1: "MLM ÖZELLİKLİ",
    title2: "E-TİCARET PORTALI",
    link: "/e-ticaret",
  },
  {
    id: 7,
    url: "/assets/Images/ERP-rapor.png",
    alt: "Kentsel Dönüşüm Bilgi Sistemi",
    title1: "KENTSEL DÖNÜŞÜM",
    title2: "BİLGİ SİSTEMİ",
    link: "/kentsel-donusum",
  },
];
