export const workData = [
  {
    id: 1,
    url: "/assets/Images/yıgma.png",
    alt: "Fizibil Yığma Analiz",
    title1: "FİZİBİL",
    title2: "YIĞMA ANALİZ",
    link: "/yigma",
  },
  {
    id: 2,
    url: "/assets/Images/civil.png",
    alt: "Fizibil İskele Analizi",
    title1: "FİZİBİL",
    title2: "İSKELE ANALİZ",
    link: "/iskele",
  },
  {
    id: 3,
    url: "/assets/Images/ERP-rapor.png",
    alt: "ERP Yazılım ve Danışmanlık",
    title1: "ERP YAZILIM VE",
    title2: "DANIŞMANLIK",
    link: "/erp",
  },
  {
    id: 4,
    url: "/assets/Images/ERP-rapor.png",
    alt: "MLM Özellikli E-Ticaret Portalı",
    title1: "MLM ÖZELLİKLİ",
    title2: "E-TİCARET PORTALI",
    link: "/e-ticaret",
  },
  {
    id: 5,
    url: "/assets/Images/ERP-rapor.png",
    alt: "Kentsel Dönüşüm Bilgi Sistemi",
    title1: "KENTSEL DÖNÜŞÜM",
    title2: "BİLGİ SİSTEMİ",
    link: "/kentsel-donusum",
  },
  {
    id: 6,
    url: "/assets/Images/medikal.png",
    alt: "Magenta Ayak Analizi",
    title1: "MAGENTA",
    title2: "AYAK ANALİZİ",
    link: "/ayak-analiz",
  },
  {
    id: 7,
    url: "/assets/Images/ERP-rapor.png",
    alt: "Statik Proje Bedeli Hesaplama",
    title1: "STATİK PROJE BEDELİ",
    title2: "HESAPLAMA",
    link: "/proje-bedel",
  },
];
